#!/bin/sh

get_iface () {
	local interface=$1
	local iface=$(uci get network.$interface.ifname)
	local type=$(uci -q get network.$interface.type)
	[ "bridge" = "$type" ] && iface="br-$interface"
	echo $iface
}

TestHosts="8.8.8.8 78.47.165.13 144.76.72.180 5.9.112.157 78.24.191.177"
PingTrials=20
IFace=$(get_iface wan)

iftest () {
    ifconfig $1 2>/dev/null | grep -q RUNNING
}

pingtest () {
    # TODO: replace with something parallel
    for i in $(seq 1 $PingTrials); do
	for h in $2; do
	    ping -c 1 -w 5 -I $1  $h &>/dev/null
	    if [ $? -eq 0 ]; then
		exit 0;	
	    fi
	done
    done
}

case "$1" in
    internet)
	iftest $IFace && pingtest $IFace $TestHosts
	;;
    vpn)
	IFace=tun0
	iftest $IFace && pingtest $IFace $TestHosts
	;;
    *)
	echo "Usage:
$0 <internet|vpn>" >&2
	exit 1
	;;
esac

#Bail out if something fails
exit 1
